### PR TITLE
Created User and Org Models

### PR DESCRIPTION
**Pull request by Garvit1809**

### CODE REVIEW

**Review by ArunBohra12 — COMMENTED** [review]
`module.exports` only works in `commonjs` modules however we are using `es modules`

Please change your module.exports to 
`export const functionName = () => ...`

**Review by ArunBohra12 — CHANGES_REQUESTED** [review]
Pls change the way you export functions

**Comment by Garvit1809** [comment]
Okkk Got it

**Review by ArunBohra12 — APPROVED** [review]
LGTM

**Pull request merged**
